build_script:
  - ps: .\build.ps1 -Nightly
test_script:
  - ps: .\test\test.ps1 -Nightly
branches:
  only:
    - master
    - staging
    - dev
    - /^(.*\/)?ci-.*$/
deploy: off
os: Visual Studio 2017
